In [3]:
import numpy as np
import pandas as pd
from encoders.encoders import SharedDomainEncoder
from encoders.workload_generator import generate_relation_flexible

In [9]:
print("--- Starting Matrix Join Experiment ---")

# --- 1. Define Domains and Parameters ---
SPARSITY_R = 0.1
SPARSITY_S = 0.7
NUM_USERS = 20
NUM_PRODUCTS = 5
NUM_CATEGORIES = 4

# Define the domains explicitly
user_domain = [f'user_{i}' for i in range(1, NUM_USERS + 1)]
product_domain = [f'prod_{chr(65 + i)}' for i in range(NUM_PRODUCTS)] # 'prod_A', 'prod_B', ...
category_domain = [f'cat_{i}' for i in range(1, NUM_CATEGORIES + 1)]

# --- 2. Generate Synthetic Data ---
print(f"\nGenerating relations...")

# Table R maps: Users -> Products
df_R = generate_relation_flexible(user_domain, product_domain, 'UserID', 'ProductID', sparsity=SPARSITY_R, seed=42)

# Table S maps: Products -> Categories
df_S = generate_relation_flexible(product_domain, category_domain, 'ProductID', 'Category', sparsity=SPARSITY_S, seed=101)


print("\n--- Sample of Table R (UserID -> ProductID) ---")
display(df_R.head())


print("\n--- Sample of Table S (ProductID -> Category) ---")
display(df_S.head())

print("********************")
print(df_R.shape)
print(df_S.shape)

--- Starting Matrix Join Experiment ---

Generating relations...

--- Sample of Table R (UserID -> ProductID) ---

    UserID ProductID
0   user_4    prod_E
1  user_15    prod_B
2  user_19    prod_E
3  user_20    prod_B
4   user_2    prod_E

--- Sample of Table S (ProductID -> Category) ---

  ProductID Category
0    prod_A    cat_2
1    prod_C    cat_1
2    prod_E    cat_2
3    prod_B    cat_4
4    prod_E    cat_1

********************
(10, 2)
(14, 2)